// automatically generated by the FlatBuffers compiler, do not modify

package herddb.proto.flatbuf;

public final class AnyValue {
  private AnyValue() { }
  public static final byte NONE = 0;
  public static final byte IntValue = 1;
  public static final byte LongValue = 2;
  public static final byte StringValue = 3;
  public static final byte BooleanValue = 4;
  public static final byte DoubleValue = 5;
  public static final byte NullValue = 6;
  public static final byte TimestampValue = 7;

  public static final String[] names = { "NONE", "IntValue", "LongValue", "StringValue", "BooleanValue", "DoubleValue", "NullValue", "TimestampValue", };

  public static String name(int e) { return names[e]; }
}

