// automatically generated by the FlatBuffers compiler, do not modify

package herddb.proto.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class BooleanValue extends Table {
  public static BooleanValue getRootAsBooleanValue(ByteBuffer _bb) { return getRootAsBooleanValue(_bb, new BooleanValue()); }
  public static BooleanValue getRootAsBooleanValue(ByteBuffer _bb, BooleanValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public BooleanValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean value() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createBooleanValue(FlatBufferBuilder builder,
      boolean value) {
    builder.startObject(1);
    BooleanValue.addValue(builder, value);
    return BooleanValue.endBooleanValue(builder);
  }

  public static void startBooleanValue(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, boolean value) { builder.addBoolean(0, value, false); }
  public static int endBooleanValue(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

