// automatically generated by the FlatBuffers compiler, do not modify

package herddb.proto.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class IntValue extends Table {
  public static IntValue getRootAsIntValue(ByteBuffer _bb) { return getRootAsIntValue(_bb, new IntValue()); }
  public static IntValue getRootAsIntValue(ByteBuffer _bb, IntValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public IntValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int value() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createIntValue(FlatBufferBuilder builder,
      int value) {
    builder.startObject(1);
    IntValue.addValue(builder, value);
    return IntValue.endIntValue(builder);
  }

  public static void startIntValue(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, int value) { builder.addInt(0, value, 0); }
  public static int endIntValue(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

