// automatically generated by the FlatBuffers compiler, do not modify

package herddb.proto.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MapEntry extends Table {
  public static MapEntry getRootAsMapEntry(ByteBuffer _bb) { return getRootAsMapEntry(_bb, new MapEntry()); }
  public static MapEntry getRootAsMapEntry(ByteBuffer _bb, MapEntry obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MapEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String key() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer keyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer keyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public AnyValueWrapper value() { return value(new AnyValueWrapper()); }
  public AnyValueWrapper value(AnyValueWrapper obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createMapEntry(FlatBufferBuilder builder,
      int keyOffset,
      int valueOffset) {
    builder.startObject(2);
    MapEntry.addValue(builder, valueOffset);
    MapEntry.addKey(builder, keyOffset);
    return MapEntry.endMapEntry(builder);
  }

  public static void startMapEntry(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addKey(FlatBufferBuilder builder, int keyOffset) { builder.addOffset(0, keyOffset, 0); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(1, valueOffset, 0); }
  public static int endMapEntry(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

