// automatically generated by the FlatBuffers compiler, do not modify

package herddb.proto.flatbuf;

public final class MessageType {
  private MessageType() { }
  public static final byte TYPE_ACK = 0;
  public static final byte TYPE_CLIENT_SHUTDOWN = 3;
  public static final byte TYPE_ERROR = 4;
  public static final byte TYPE_EXECUTE_STATEMENT = 5;
  public static final byte TYPE_EXECUTE_STATEMENT_RESULT = 6;
  public static final byte TYPE_OPENSCANNER = 7;
  public static final byte TYPE_RESULTSET_CHUNK = 8;
  public static final byte TYPE_CLOSESCANNER = 9;
  public static final byte TYPE_FETCHSCANNERDATA = 10;
  public static final byte TYPE_REQUEST_TABLESPACE_DUMP = 11;
  public static final byte TYPE_TABLESPACE_DUMP_DATA = 12;
  public static final byte TYPE_REQUEST_TABLE_RESTORE = 13;
  public static final byte TYPE_PUSH_TABLE_DATA = 14;
  public static final byte TYPE_EXECUTE_STATEMENTS = 15;
  public static final byte TYPE_EXECUTE_STATEMENTS_RESULT = 16;
  public static final byte TYPE_PUSH_TXLOGCHUNK = 17;
  public static final byte TYPE_TABLE_RESTORE_FINISHED = 19;
  public static final byte TYPE_PUSH_TRANSACTIONSBLOCK = 20;
  public static final byte TYPE_RESTORE_FINISHED = 23;
  public static final byte TYPE_TX_COMMAND = 24;
  public static final byte TYPE_SASL_TOKEN_MESSAGE_REQUEST = 100;
  public static final byte TYPE_SASL_TOKEN_SERVER_RESPONSE = 101;
  public static final byte TYPE_SASL_TOKEN_MESSAGE_TOKEN = 102;

  public static final String[] names = { "TYPE_ACK", "", "", "TYPE_CLIENT_SHUTDOWN", "TYPE_ERROR", "TYPE_EXECUTE_STATEMENT", "TYPE_EXECUTE_STATEMENT_RESULT", "TYPE_OPENSCANNER", "TYPE_RESULTSET_CHUNK", "TYPE_CLOSESCANNER", "TYPE_FETCHSCANNERDATA", "TYPE_REQUEST_TABLESPACE_DUMP", "TYPE_TABLESPACE_DUMP_DATA", "TYPE_REQUEST_TABLE_RESTORE", "TYPE_PUSH_TABLE_DATA", "TYPE_EXECUTE_STATEMENTS", "TYPE_EXECUTE_STATEMENTS_RESULT", "TYPE_PUSH_TXLOGCHUNK", "", "TYPE_TABLE_RESTORE_FINISHED", "TYPE_PUSH_TRANSACTIONSBLOCK", "", "", "TYPE_RESTORE_FINISHED", "TYPE_TX_COMMAND", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "TYPE_SASL_TOKEN_MESSAGE_REQUEST", "TYPE_SASL_TOKEN_SERVER_RESPONSE", "TYPE_SASL_TOKEN_MESSAGE_TOKEN", };

  public static String name(int e) { return names[e]; }
}

