// automatically generated by the FlatBuffers compiler, do not modify

package herddb.proto.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class NullValue extends Table {
  public static NullValue getRootAsNullValue(ByteBuffer _bb) { return getRootAsNullValue(_bb, new NullValue()); }
  public static NullValue getRootAsNullValue(ByteBuffer _bb, NullValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public NullValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long value() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createNullValue(FlatBufferBuilder builder,
      long value) {
    builder.startObject(1);
    NullValue.addValue(builder, value);
    return NullValue.endNullValue(builder);
  }

  public static void startNullValue(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, long value) { builder.addLong(0, value, 0L); }
  public static int endNullValue(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

