// automatically generated by the FlatBuffers compiler, do not modify

package herddb.proto.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TableDefinition extends Table {
  public static TableDefinition getRootAsTableDefinition(ByteBuffer _bb) { return getRootAsTableDefinition(_bb, new TableDefinition()); }
  public static TableDefinition getRootAsTableDefinition(ByteBuffer _bb, TableDefinition obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TableDefinition __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte schema(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int schemaLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer schemaAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer schemaInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createTableDefinition(FlatBufferBuilder builder,
      int schemaOffset) {
    builder.startObject(1);
    TableDefinition.addSchema(builder, schemaOffset);
    return TableDefinition.endTableDefinition(builder);
  }

  public static void startTableDefinition(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addSchema(FlatBufferBuilder builder, int schemaOffset) { builder.addOffset(0, schemaOffset, 0); }
  public static int createSchemaVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startSchemaVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endTableDefinition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

