// automatically generated by the FlatBuffers compiler, do not modify

package herddb.proto.flatbuf;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TimestampValue extends Table {
  public static TimestampValue getRootAsTimestampValue(ByteBuffer _bb) { return getRootAsTimestampValue(_bb, new TimestampValue()); }
  public static TimestampValue getRootAsTimestampValue(ByteBuffer _bb, TimestampValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public TimestampValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long value() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createTimestampValue(FlatBufferBuilder builder,
      long value) {
    builder.startObject(1);
    TimestampValue.addValue(builder, value);
    return TimestampValue.endTimestampValue(builder);
  }

  public static void startTimestampValue(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addValue(FlatBufferBuilder builder, long value) { builder.addLong(0, value, 0L); }
  public static int endTimestampValue(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

